In [1]:
import numpy as np # importing the numpy library

In [2]:
# this creates a numpy array object
data = np.array([[1.5, -0.1, 3], 
                 [0, -3, 6.5]])

data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [3]:
# multiple each entry in the array obj by 10 
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [4]:
# element-wise summation 
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [12]:
print(data.shape, data.dtype, type(data), end="\n")


(2, 3) float64 <class 'numpy.ndarray'>


In [13]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [14]:
data2 = [[1, 2, 3, 4],
        [5, 6, 7, 8]]
arr2 = np.array(data2)
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [17]:
# dimension of an array, this is the same as the number 
# rows in the array
# equivalent to 'arr2.shape[0]'
arr2.ndim

2

In [26]:
# creating array with zero elements using 'ones', 'zeros' and 'empty'

np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [33]:
np.empty((2, 3, 2))# doesn't really produses an empty array

array([[[4.66096671e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [6.95859322e-239, 3.46670710e+179]],

       [[6.59450123e-066, 1.25666921e-075],
        [1.52851722e+160, 6.11678594e+169],
        [2.21549574e-052, 7.10966550e-038]]])

In [34]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
np.full((2,3,5), fill_value=0)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [45]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
arr1 = np.array([1, 2,3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [55]:
arr2 = np.array(np.full((2,3), fill_value=2.0), dtype=np.int32)
arr2.dtype

dtype('int32')

#### Arithmetic with Numpy Arrays

In [62]:
arr = np.array([np.arange(1,4), np.arange(4,7)], dtype=np.int32)
arr

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [63]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [64]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [65]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [66]:
arr ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [67]:
arr2 = np.array([[0, 4, 1], [7, 2, 12]], dtype=np.float16)
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]], dtype=float16)

In [68]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

#### Basic Indexing and Slicing

In [69]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
arr[5]

5

In [72]:
arr[5:8] # get the elements from th 5th to 'n-1' element

array([5, 6, 7])

In [74]:
arr[5:8] = 12 # changing index value
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [78]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [79]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [80]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [92]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [94]:
arr3d[:, :, 1]

array([[ 2,  5],
       [ 8, 11]])

In [ ]:
# to get the number 11
arr3d[1, 1,1] # outputs 11

11

In [ ]:
arr3d[0,1 , 2] # outputs 6

6

In [86]:
arr2d = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
arr2d[:, 1]

array([2, 5, 8])